name: 'claims_mart'
version: '1.0.0'
config-version: 2

profile: 'claims_mart'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:         
  - "target"
  - "dbt_packages"

seeds:
  claims_mart:
    unit_testing:
        schema: unit_testing
        +tags:
          - unit_testing

on-run-start:
    - '{{create_functions()}}'
    - '{{change_datestyle()}}'
    - '{{create_source_tables()}}'
