version: "3.8"
services:
  postgres:
    container_name: postgres-dbt
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  pgadmin:
    container_name: pgadmin-dbt
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
