import csv
import random
import sys
from datetime import datetime, timedelta


if len(sys.argv) != 4:
    print("Wrong number of arguments")
    sys.exit(1)


try:
    rows_number = int(sys.argv[1])
    data_quality_percentage = int(sys.argv[2])
    data_duplicates_percentage = int(sys.argv[3])
except ValueError:
    print("Bad arguments")
    sys.exit(1)


def random_day():
    start_date = datetime(2015, 1, 1)
    end_date = datetime(2023, 9, 16)
    random_date = start_date + timedelta(
        days=random.randint(0, (end_date - start_date).days)
    )
    return random_date.strftime("%d/%m/%Y")

def random_datetime():
    random_day_value = random_day()
    random_time = timedelta(
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
        seconds=random.randint(0, 59)
    )
    random_datetime_value = str(random_day_value) + " " + str(random_time)
    return random_datetime_value


def random_color():
    return random.choice(
        [
            "Red",
            "Blue",
            "Green",
            "Yellow",
            "Orange",
            "Purple",
            "Pink",
            "Brown",
            "Black",
            "White",
            "Gray",
            "Silver",
            "Gold",
            "Indigo",
            "Turquoise",
            "Lavender",
            "Maroon",
            "Teal",
            "Beige",
            "Cyan",
            "Magenta",
            "Olive",
            "Salmon",
            "Coral",
            "Plum",
            "Ruby",
            "Slate",
            "Charcoal",
            "Ivory",
            "Tan",
        ]
    )


def repair_cost(tld, pav):
    if tld == "Repair":
        return random.randint(1, int(pav))
    elif tld == "TotalLoss":
        return random.randint(int(pav), 10 * int(pav))
    else:
        return random.randint(11 * int(pav), 13 * int(pav)) / 10


def random_vehicle_number():
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    numbers = "0123456789"
    letter1 = random.choice(letters)
    letter2 = random.choice(letters)
    letter3 = random.choice(letters)
    num1 = random.choice(numbers)
    num2 = random.choice(numbers)
    num3 = random.choice(numbers)
    num4 = random.choice(numbers)
    return f"{letter1}{letter2}{letter3} {num1}{num2}{num3}{num4}"


def policy_number():
    prefix = random.choice(["CHB", "IWV", "ZOC", "PRC", "WZE"])
    number = random.randint(100000, 999999)
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    letter1 = random.choice(letters)
    letter2 = random.choice(letters)
    return f"{prefix}{number}{letter1}{letter2}"


def random_model():
    return random.choice(
        [
            "Camry",
            "Focus",
            "Civic",
            "Silverado",
            "Jetta",
            "Altima",
            "3 Series",
            "E-Class",
            "A4",
            "Elantra",
            "Sorento",
            "Outback",
            "Model S",
            "CX-5",
            "500",
            "XC60",
            "F-PACE",
            "Range Rover Sport",
            "911",
            "Escalade",
            "Sierra",
            "300",
            "Challenger",
            "Wrangler",
            "1500",
            "Outlander",
            "RX",
            "Q50",
            "ILX",
            "Enclave",
            "Cooper",
            "Stelvio",
            "Ghibli",
            "Phantom",
            "Continental",
            "DB11",
            "570S",
            "Chiron",
            "488 GTB",
            "Huracan",
            "Civic",
            "Mustang",
            "Cruze",
            "Golf",
            "Maxima",
            "5 Series",
            "C-Class",
            "A6",
            "Sonata",
            "Sportage",
            "Legacy",
            "Model 3",
            "CX-9",
            "Crosstrek",
            "Model X",
            "MX-5 Miata",
            "500X",
            "S60",
            "XF",
            "Range Rover",
            "Cayenne",
            "XT5",
            "Yukon",
            "Pacifica",
            "Durango",
            "Renegade",
            "Canyon",
            "Touareg",
            "Journey",
            "Escape",
            "Rav4",
            "Corolla",
            "Explorer",
            "Malibu",
            "Passat",
            "Murano",
            "4 Series",
            "CLA",
            "Q3",
            "Kona",
            "Optima",
            "Impreza",
            "Model Y",
            "CX-30",
            "Ascent",
            "S4",
            "MDX",
            "Encore",
            "Clubman",
            "Giulia",
            "GranTurismo",
            "Ghost",
            "Flying Spur",
            "Vantage",
            "720S",
            "La Voiture Noire",
            "812 Superfast",
            "Huracan",
            "Civic",
            "Mustang",
            "Cruze",
            "Golf",
            "Maxima",
            "5 Series",
            "C-Class",
            "A6",
            "Sonata",
            "Sportage",
            "Legacy",
            "Model 3",
            "CX-9",
            "Crosstrek",
            "Model X",
            "MX-5 Miata",
            "500X",
            "S60",
            "XF",
            "Range Rover",
            "Cayenne",
            "XT5",
            "Yukon",
            "Pacifica",
            "Durango",
            "Renegade",
            "Canyon",
            "Touareg",
            "Journey",
            "Escape",
            "Rav4",
            "Corolla",
            "Explorer",
            "Malibu",
            "Passat",
            "Murano",
            "4 Series",
            "CLA",
            "Q3",
            "Kona",
            "Optima",
            "Impreza",
            "Model Y",
            "CX-30",
            "Ascent",
            "S4",
            "MDX",
            "Encore",
            "Clubman",
            "Giulia",
            "GranTurismo",
            "Ghost",
            "Flying Spur",
            "Vantage",
            "720S",
            "La Voiture Noire",
            "812 Superfast",
            "Huracan",
            "Civic",
            "Mustang",
            "Cruze",
            "Golf",
            "Maxima",
            "5 Series",
            "C-Class",
            "A6",
            "Sonata",
            "Sportage",
            "Legacy",
            "Model 3",
            "CX-9",
            "Crosstrek",
            "Model X",
            "MX-5 Miata",
            "500X",
            "S60",
            "XF",
            "Range Rover",
            "Cayenne",
            "XT5",
            "Yukon",
            "Pacifica",
            "Durango",
            "Renegade",
            "Canyon",
            "Touareg",
            "Journey",
            "Escape",
            "Rav4",
            "Corolla",
            "Explorer",
            "Malibu",
            "Passat",
            "Murano",
            "4 Series",
            "CLA",
            "Q3",
            "Kona",
            "Optima",
            "Impreza",
            "Model Y",
            "CX-30",
            "Ascent",
            "S4",
            "MDX",
            "Encore",
            "Clubman",
            "Giulia",
            "GranTurismo",
            "Ghost",
            "Flying Spur",
            "Vantage",
            "720S",
            "La Voiture Noire",
            "812 Superfast",
        ]
    )


def random_make():
    return random.choice(
        [
            "Toyota",
            "Ford",
            "Honda",
            "Chevrolet",
            "Volkswagen",
            "Nissan",
            "BMW",
            "Mercedes-Benz",
            "Audi",
            "Hyundai",
            "Kia",
            "Subaru",
            "Tesla",
            "Mazda",
            "Fiat",
            "Volvo",
            "Jaguar",
            "Land Rover",
            "Porsche",
            "Cadillac",
            "GMC",
            "Chrysler",
            "Dodge",
            "Jeep",
            "Ram",
            "Mitsubishi",
            "Lexus",
            "Infiniti",
            "Acura",
            "Buick",
            "Mini",
            "Alfa Romeo",
            "Maserati",
            "Rolls-Royce",
            "Bentley",
            "Aston Martin",
            "McLaren",
            "Bugatti",
            "Ferrari",
            "Lamborghini",
        ]
    )


def random_damage():
    return random.choice(
        [
            "Front bumper dent",
            "Rear bumper scratch",
            "Dented hood",
            "Cracked windshield",
            "Scratched paint",
            "Broken taillight",
            "Dented fender",
            "Broken side mirror",
            "Hail damage",
            "Keyed doors",
            "Flat tire",
            "Broken headlight",
            "Side door dent",
            "Rearview mirror missing",
            "Broken window",
            "Fender bender damage",
            "Rear bumper dent",
            "Side mirror scratch",
            "Tire puncture",
            "Hood scratch",
            "Dented roof",
            "Dented trunk",
            "Scratched door handle",
            "Dented quarter panel",
            "Broken antenna",
            "Scraped side panel",
            "Dented grille",
            "Scratched fender",
            "Paint chips",
            "Bent rim",
            "Side door ding",
            "Rear quarter panel damage",
            "Broken tailpipe",
            "Cracked side window",
            "Side mirror missing",
            "Keyed trunk",
            "Roof dent",
            "Fender bender",
            "Dented rocker panel",
            "Scratched roof",
            "Bent frame",
            "Door dent",
            "Paint scuffs",
            "Hood damage",
            "Scratched bumper",
            "Dented rear door",
            "Tire damage",
            "Bumper scratch",
            "Broken side window",
            "Scratched quarter panel",
            "Roof scratch",
            "Broken side mirror glass",
            "Dented front door",
            "Rear bumper scratch",
            "Scratched trunk",
            "Cracked taillight",
            "Dented quarter panel",
            "Fender damage",
            "Side mirror dent",
            "Paint swirls",
            "Chipped windshield",
            "Rear door dent",
            "Scratched rocker panel",
            "Bent bumper",
            "Broken roof antenna",
            "Dinged quarter panel",
            "Door handle scratch",
            "Dented tailgate",
            "Rear fender damage",
            "Scratched grille",
            "Keyed fender",
            "Broken roof rack",
            "Scratched side door",
            "Front bumper scratch",
            "Bent side mirror",
            "Dented rear quarter panel",
            "Rear bumper damage",
            "Paint peeling",
            "Cracked windshield washer nozzle",
            "Fender dent",
            "Scratched rear door",
            "Side panel dent",
            "Broken grille",
            "Scratched rocker panel",
            "Keyed roof",
            "Dented rear bumper",
            "Tailgate dent",
            "Hood dent",
            "Broken door handle",
            "Dented rear quarter panel",
            "Roof rack damage",
            "Chipped paint",
            "Scratched front door",
            "Side mirror chip",
            "Front bumper damage",
            "Dented side panel",
            "Scratched rear bumper",
            "Broken wheel cover",
            "Dented rocker panel",
            "Dinged rear door",
            "Bent roof rack",
            "Roof scratch",
            "Scratched side mirror",
            "Keyed quarter panel",
            "Trunk dent",
            "Broken hood latch",
            "Scratched rear quarter panel",
            "Bumper dent",
            "Dented side door",
            "Rearview mirror scratch",
            "Dinged quarter panel",
            "Rear door scratch",
            "Broken tailgate handle",
            "Fender scratch",
            "Roof dent",
            "Chipped windshield",
            "Scratched side panel",
            "Bent bumper cover",
            "Door handle damage",
            "Rear quarter panel dent",
            "Broken roof rail",
            "Scratched door frame",
            "Front bumper dent",
            "Bent rear bumper",
            "Tailgate damage",
            "Dented side quarter panel",
            "Scratched trunk lid",
            "Fender bender damage",
            "Side mirror damage",
            "Keyed roof rack",
            "Dinged front door",
            "Rear bumper dent",
            "Roof rack scratch",
            "Paint oxidation",
            "Cracked bumper cover",
            "Scratched rocker panel",
            "Hood chip",
            "Bent roof rail",
            "Broken door frame",
            "Rear door dent",
            "Bumper scuffs",
            "Dented side rocker panel",
            "Trunk scratch",
            "Front bumper scrape",
            "Dinged rear quarter panel",
            "Roof rack dent",
            "Scratched quarter window",
            "Dented side sill",
            "Fender bender dent",
            "Broken roof rail cover",
            "Rear bumper chip",
            "Scratched door sill",
            "Keyed side mirror",
            "Dented quarter window",
            "Chipped door frame",
            "Side mirror dent",
            "Rear quarter panel scratch",
            "Trunk lid dent",
            "Roof rail damage",
            "Bent quarter window",
            "Hood scuffs",
            "Dented door sill",
            "Broken rocker panel",
            "Front bumper ding",
            "Scratched side sill",
            "Tailgate chip",
            "Rear bumper scuffs",
            "Paint swirl marks",
            "Dinged door sill",
            "Bumper scrape",
            "Side mirror scrape",
            "Bent quarter sill",
            "Scratched door sill",
            "Chipped side mirror",
            "Roof rail dent",
            "Dented quarter sill",
            "Fender bender scrape",
            "Broken quarter sill",
            "Rear bumper scrape",
            "Hood ding",
            "Scratched quarter sill",
            "Bent rear quarter sill",
            "Roof rack scrape",
            "Dented side window",
            "Front bumper chip",
            "Tailgate scrape",
            "Dinged quarter sill",
            "Scratched roof rail",
            "Chipped quarter sill",
            "Side mirror ding",
            "Bent quarter panel sill",
            "Broken quarter panel sill",
            "Bumper ding",
            "Rear bumper ding",
            "Scratched rear sill",
            "Dented rear sill",
            "Roof dent",
            "Front bumper scuffs",
            "Side mirror chip",
            "Broken quarter window sill",
            "Tailgate ding",
            "Dinged rear sill",
            "Scratched door handle sill",
            "Chipped rear quarter sill",
            "Bent door sill",
            "Roof rack chip",
            "Dented door handle sill",
            "Fender bender scuffs",
            "Broken door handle sill",
            "Rear bumper scuffs",
            "Front bumper ding",
            "Scratched side window sill",
            "Bumper dent",
            "Tailgate dent",
            "Side mirror scuffs",
            "Dinged quarter window sill",
            "Roof rack ding",
            "Chipped side window sill",
            "Broken quarter sill",
            "Dented quarter window sill",
            "Fender scratch",
            "Front bumper scrape",
            "Tailgate chip",
            "Roof dent",
            "Rear bumper scrape",
            "Side mirror ding",
            "Bumper scrape",
            "Dinged door handle sill",
            "Scratched roof rack sill",
            "Chipped door handle sill",
            "Broken roof rail sill",
            "Roof rack scrape",
            "Dented roof sill",
            "Fender bender chip",
            "Front bumper ding",
            "Tailgate scrape",
            "Rear bumper chip",
            "Scratched door frame sill",
            "Bent roof rail sill",
            "Side mirror scrape",
            "Dented side window sill",
            "Bumper scuffs",
            "Roof rail chip",
            "Chipped roof sill",
            "Broken quarter window sill",
            "Front bumper chip",
            "Tailgate scrape",
            "Roof rack scuffs",
            "Dinged roof sill",
            "Rear bumper ding",
            "Scratched quarter window sill",
            "Bumper scrape",
            "Broken side mirror sill",
            "Chipped bumper sill",
            "Fender bender scrape",
            "Front bumper sill",
            "Tailgate chip",
            "Roof rack dent",
            "Rear bumper scuffs",
            "Dinged quarter sill",
            "Scratched roof sill",
            "Bumper ding",
            "Broken roof rack sill",
            "Side mirror sill",
            "Dented roof rack sill",
            "Chipped roof rack sill",
            "Roof sill dent",
            "Fender dent",
            "Front bumper scuffs",
            "Tailgate scrape",
            "Bumper scrape",
            "Rear bumper dent",
            "Scratched quarter sill",
            "Dinged roof rack sill",
            "Bent roof sill",
            "Broken side mirror sill",
            "Roof rack sill",
            "Chipped roof sill",
            "Dented roof sill",
            "Fender bender scuffs",
            "Front bumper dent",
            "Tailgate chip",
            "Scratched side mirror sill",
            "Rear bumper scrape",
            "Bumper scuffs",
            "Roof rack chip",
            "Chipped bumper sill",
            "Dented bumper sill",
            "Side mirror ding",
            "Roof sill chip",
            "Dinged bumper sill",
            "Scratched roof rack sill",
            "Bent roof rack sill",
            "Front bumper scrape",
            "Tailgate ding",
            "Rear bumper chip",
            "Dented quarter sill",
            "Scratched roof sill",
            "Bumper dent",
            "Broken roof sill",
            "Side mirror scrape",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Dinged roof sill",
            "Front bumper sill",
            "Tailgate scrape",
            "Scratched quarter sill",
            "Bent quarter sill",
            "Bumper scrape",
            "Roof dent",
            "Rear bumper sill",
            "Side mirror scuffs",
            "Dented bumper sill",
            "Fender scratch",
            "Front bumper ding",
            "Tailgate chip",
            "Roof rack scrape",
            "Chipped quarter sill",
            "Scratched roof sill",
            "Bumper ding",
            "Rear bumper scuffs",
            "Roof sill dent",
            "Side mirror ding",
            "Front bumper chip",
            "Tailgate scrape",
            "Broken quarter sill",
            "Dinged quarter sill",
            "Bent door sill",
            "Bumper scrape",
            "Roof rack dent",
            "Roof sill chip",
            "Fender bender chip",
            "Front bumper ding",
            "Tailgate chip",
            "Side mirror sill",
            "Rear bumper scrape",
            "Chipped door sill",
            "Roof rack scuffs",
            "Dented roof sill",
            "Broken side window sill",
            "Bumper dent",
            "Front bumper scuffs",
            "Tailgate dent",
            "Roof sill dent",
            "Side mirror chip",
            "Rear bumper chip",
            "Roof rack chip",
            "Chipped roof sill",
            "Bent roof sill",
            "Front bumper dent",
            "Tailgate scrape",
            "Dented quarter sill",
            "Bumper scuffs",
            "Roof rack scrape",
            "Fender bender dent",
            "Roof dent",
            "Rear bumper dent",
            "Front bumper scrape",
            "Tailgate chip",
            "Chipped bumper sill",
            "Side mirror scrape",
            "Dinged door sill",
            "Bumper ding",
            "Roof rack sill",
            "Scratched roof rack sill",
            "Roof sill chip",
            "Chipped quarter sill",
            "Broken roof rack sill",
            "Bent roof rack sill",
            "Bumper scrape",
            "Roof dent",
            "Front bumper dent",
            "Rear bumper scrape",
            "Tailgate scrape",
            "Roof rack chip",
            "Dented roof rack sill",
            "Dinged roof sill",
            "Roof sill dent",
            "Chipped roof sill",
            "Side mirror sill",
            "Bent bumper sill",
            "Broken side mirror scrape",
            "Bumper dent",
            "Roof rack dent",
            "Chipped bumper scrape",
            "Scratched roof sill",
            "Roof rack sill",
            "Roof sill chip",
            "Front bumper scrape",
            "Rear bumper scrape",
            "Tailgate dent",
            "Roof dent",
            "Dinged roof rack sill",
            "Bent roof sill",
            "Side mirror scrape",
            "Dented bumper scrape",
            "Roof rack scuffs",
            "Broken roof sill",
            "Chipped roof sill",
            "Front bumper sill",
            "Roof rack dent",
            "Tailgate scrape",
            "Roof sill dent",
            "Chipped quarter sill",
            "Dinged roof sill",
            "Roof rack scrape",
            "Bumper ding",
            "Roof dent",
            "Front bumper chip",
            "Tailgate dent",
            "Rear bumper dent",
            "Scratched roof sill",
            "Roof rack sill",
            "Roof sill chip",
            "Chipped roof sill",
            "Bent roof rack sill",
            "Broken bumper sill",
            "Dented bumper ding",
            "Front bumper dent",
            "Tailgate scrape",
            "Roof rack dent",
            "Roof sill dent",
            "Bumper scrape",
            "Chipped quarter sill",
            "Dinged roof sill",
            "Broken roof rack sill",
            "Roof rack scrape",
            "Side mirror dent",
            "Roof dent",
            "Front bumper scrape",
            "Tailgate chip",
            "Roof sill dent",
            "Dented roof sill",
            "Bumper dent",
            "Roof rack dent",
            "Chipped bumper sill",
            "Roof rack scrape",
            "Chipped roof sill",
            "Scratched bumper sill",
            "Bent roof rack sill",
            "Front bumper scrape",
            "Tailgate dent",
            "Roof rack chip",
            "Dinged roof sill",
            "Roof sill chip",
            "Roof rack scuffs",
            "Dented bumper dent",
            "Roof dent",
            "Rear bumper scrape",
            "Front bumper sill",
            "Tailgate scrape",
            "Roof rack scrape",
            "Roof sill dent",
            "Bumper scrape",
            "Roof rack dent",
            "Chipped roof sill",
            "Dinged roof sill",
            "Roof sill chip",
            "Bent roof rack sill",
            "Broken roof rack sill",
            "Front bumper dent",
            "Tailgate dent",
            "Roof dent",
            "Rear bumper scrape",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Dented roof sill",
            "Roof rack scrape",
            "Roof sill dent",
            "Chipped roof sill",
            "Front bumper scrape",
            "Tailgate chip",
            "Roof rack chip",
            "Dinged roof sill",
            "Roof rack scuffs",
            "Broken bumper sill",
            "Roof sill chip",
            "Roof dent",
            "Front bumper dent",
            "Rear bumper dent",
            "Tailgate scrape",
            "Bumper dent",
            "Roof rack dent",
            "Chipped bumper sill",
            "Roof rack scrape",
            "Roof sill dent",
            "Chipped roof sill",
            "Roof rack sill",
            "Front bumper chip",
            "Tailgate scrape",
            "Roof dent",
            "Dented roof sill",
            "Bumper scrape",
            "Roof rack dent",
            "Chipped roof sill",
            "Dinged roof sill",
            "Roof sill chip",
            "Bent roof rack sill",
            "Roof rack scuffs",
            "Front bumper scrape",
            "Rear bumper scrape",
            "Roof rack chip",
            "Roof sill dent",
            "Chipped bumper scrape",
            "Bumper dent",
            "Roof rack scrape",
            "Roof dent",
            "Front bumper dent",
            "Tailgate dent",
            "Roof rack dent",
            "Chipped bumper sill",
            "Roof sill dent",
            "Dinged roof sill",
            "Chipped roof sill",
            "Roof rack scuffs",
            "Front bumper scrape",
            "Tailgate chip",
            "Roof rack chip",
            "Bent roof rack sill",
            "Roof sill chip",
            "Roof rack sill",
            "Roof dent",
            "Dented roof sill",
            "Rear bumper dent",
            "Scratched roof sill",
            "Bumper scrape",
            "Roof rack dent",
            "Chipped roof sill",
            "Dinged roof sill",
            "Roof rack scrape",
            "Chipped bumper scrape",
            "Front bumper dent",
            "Roof rack scuffs",
            "Roof sill dent",
            "Bumper dent",
            "Front bumper scrape",
            "Tailgate scrape",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Roof sill dent",
            "Dinged roof sill",
            "Chipped roof sill",
            "Roof rack chip",
            "Roof rack scuffs",
            "Front bumper scrape",
            "Roof sill chip",
            "Tailgate chip",
            "Bent roof rack sill",
            "Roof dent",
            "Dented roof sill",
            "Rear bumper scrape",
            "Roof rack dent",
            "Bumper scrape",
            "Chipped roof sill",
            "Dinged roof sill",
            "Roof rack scrape",
            "Chipped bumper scrape",
            "Roof sill dent",
            "Front bumper dent",
            "Roof dent",
            "Tailgate dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Roof sill dent",
            "Dinged roof sill",
            "Roof rack chip",
            "Front bumper scrape",
            "Roof rack scuffs",
            "Roof sill chip",
            "Bent roof rack sill",
            "Roof dent",
            "Rear bumper dent",
            "Bumper dent",
            "Roof rack dent",
            "Chipped bumper scrape",
            "Dented roof sill",
            "Roof sill dent",
            "Roof rack scrape",
            "Front bumper dent",
            "Roof rack chip",
            "Roof sill dent",
            "Tailgate scrape",
            "Chipped bumper sill",
            "Roof dent",
            "Roof rack scuffs",
            "Roof rack dent",
            "Bumper scrape",
            "Roof rack chip",
            "Chipped roof sill",
            "Dinged roof sill",
            "Front bumper scrape",
            "Roof rack scrape",
            "Roof dent",
            "Roof sill chip",
            "Dented roof sill",
            "Chipped bumper scrape",
            "Roof sill dent",
            "Roof rack dent",
            "Chipped bumper sill",
            "Front bumper dent",
            "Tailgate dent",
            "Roof rack chip",
            "Roof dent",
            "Chipped roof sill",
            "Roof sill dent",
            "Bumper dent",
            "Roof rack dent",
            "Roof rack scuffs",
            "Roof rack scrape",
            "Chipped bumper scrape",
            "Roof sill chip",
            "Dinged roof sill",
            "Roof dent",
            "Dented roof sill",
            "Front bumper scrape",
            "Roof rack dent",
            "Bent roof rack sill",
            "Chipped bumper sill",
            "Roof sill dent",
            "Chipped roof sill",
            "Roof rack chip",
            "Roof rack scuffs",
            "Roof rack scrape",
            "Front bumper dent",
            "Roof dent",
            "Roof sill dent",
            "Bumper scrape",
            "Roof rack dent",
            "Chipped bumper scrape",
            "Dinged roof sill",
            "Chipped roof rack sill",
            "Roof rack dent",
            "Roof sill chip",
            "Roof rack chip",
            "Roof dent",
            "Front bumper scrape",
            "Tailgate dent",
            "Roof rack scrape",
            "Chipped bumper sill",
            "Dented roof sill",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Roof rack dent",
            "Roof sill dent",
            "Bumper dent",
            "Roof dent",
            "Chipped bumper scrape",
            "Roof rack scrape",
            "Roof rack chip",
            "Roof rack dent",
            "Front bumper dent",
            "Roof sill chip",
            "Chipped roof rack sill",
            "Tailgate dent",
            "Roof rack scuffs",
            "Roof rack chip",
            "Roof sill dent",
            "Dinged roof sill",
            "Chipped roof sill",
            "Roof dent",
            "Chipped bumper sill",
            "Bumper scrape",
            "Roof rack dent",
            "Roof rack scrape",
            "Front bumper scrape",
            "Dented roof sill",
            "Roof rack dent",
            "Roof rack scuffs",
            "Roof rack chip",
            "Chipped roof sill",
            "Roof rack dent",
            "Roof sill dent",
            "Bumper dent",
            "Roof dent",
            "Tailgate dent",
            "Front bumper dent",
            "Roof rack scrape",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof sill chip",
            "Chipped roof rack sill",
            "Dinged roof sill",
            "Roof rack scuffs",
            "Roof dent",
            "Chipped roof sill",
            "Roof rack chip",
            "Roof rack scrape",
            "Bumper dent",
            "Roof sill dent",
            "Front bumper scrape",
            "Dented roof sill",
            "Roof rack dent",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Roof rack chip",
            "Roof rack dent",
            "Roof sill chip",
            "Roof dent",
            "Tailgate dent",
            "Chipped bumper scrape",
            "Dinged roof sill",
            "Bumper scrape",
            "Chipped roof rack sill",
            "Roof rack scrape",
            "Roof rack dent",
            "Front bumper dent",
            "Roof sill dent",
            "Roof rack chip",
            "Chipped roof sill",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack scuffs",
            "Roof rack dent",
            "Dinged roof sill",
            "Roof rack scrape",
            "Roof sill chip",
            "Bumper dent",
            "Roof dent",
            "Tailgate dent",
            "Front bumper scrape",
            "Roof rack dent",
            "Chipped roof rack sill",
            "Roof rack chip",
            "Dinged roof sill",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof sill dent",
            "Chipped roof sill",
            "Roof rack scuffs",
            "Roof rack scrape",
            "Roof dent",
            "Roof sill chip",
            "Chipped bumper sill",
            "Bumper dent",
            "Roof rack dent",
            "Front bumper dent",
            "Roof rack chip",
            "Chipped roof rack sill",
            "Roof dent",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof sill dent",
            "Roof rack scuffs",
            "Dinged roof sill",
            "Chipped roof sill",
            "Roof rack scrape",
            "Bumper dent",
            "Roof dent",
            "Tailgate dent",
            "Chipped bumper sill",
            "Roof rack chip",
            "Roof rack dent",
            "Roof sill chip",
            "Front bumper scrape",
            "Dinged roof sill",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Roof rack scrape",
            "Roof rack chip",
            "Roof dent",
            "Roof sill dent",
            "Bumper dent",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Roof rack dent",
            "Front bumper dent",
            "Roof rack chip",
            "Chipped roof rack sill",
            "Roof dent",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof sill chip",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Roof rack scrape",
            "Roof dent",
            "Tailgate dent",
            "Chipped bumper sill",
            "Bumper dent",
            "Roof rack dent",
            "Roof dent",
            "Front bumper scrape",
            "Roof rack chip",
            "Roof rack dent",
            "Roof sill dent",
            "Chipped roof rack sill",
            "Chipped bumper scrape",
            "Roof rack scuffs",
            "Roof dent",
            "Roof rack scrape",
            "Chipped roof sill",
            "Roof rack chip",
            "Roof rack dent",
            "Roof sill chip",
            "Bumper dent",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Front bumper dent",
            "Roof rack dent",
            "Roof dent",
            "Chipped roof rack sill",
            "Chipped bumper scrape",
            "Roof rack scuffs",
            "Chipped roof sill",
            "Roof rack scrape",
            "Roof rack chip",
            "Roof dent",
            "Roof sill dent",
            "Bumper dent",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Roof rack dent",
            "Front bumper scrape",
            "Chipped roof rack sill",
            "Roof dent",
            "Roof rack chip",
            "Chipped bumper scrape",
            "Roof rack dent",
            "Roof sill chip",
            "Chipped roof sill",
            "Roof rack scuffs",
            "Roof rack scrape",
            "Roof dent",
            "Chipped bumper sill",
            "Roof rack dent",
            "Bumper dent",
            "Roof dent",
            "Roof rack dent",
            "Front bumper dent",
        ]
    )


def generate_data(true_data):
    if true_data:
        mid = random.randint(1000000000000, 9999999999999)
        ld = random_datetime()
        vrn = random_vehicle_number()
        y = random_datetime()
        m = random_make()
        mo = random_model()
        ec = random.randint(800, 4500)
        col = random_color()
        dd = random_damage()
        tld = random.choice(["Repair", "TotalLoss", "TotalLoss/Repair"])
        pav = random.randint(500, 100000000)
        rc = repair_cost(tld, pav)
        amfv = random.randint(10, 100000)
        pn = policy_number()
        ddob = random_day()
        ft = random.choice(
            [
                "DIESEL",
                "DIESEL/ELECTRIC",
                "DIESEL/MHEV",
                "ELECTRIC",
                "PETROL",
                "PETROL/ALCOHOL",
                "PETROL/ELECTRIC",
                "PETROL/LPG",
            ]
        )
        d = random.choice(["0", "2", "3", "4", "5", "6"])
        s = random.choice(["0", "2", "3", "4 ", "5", "6", "7", "8", "9"])
        id = random_day()
    else:
        mid = random.choice(
            [
                random.randint(1000000000000, 9999999999999),
                "",
                random_day(),
                random_model(),
            ]
        )
        ld = random.choice([random_datetime(), ""])
        vrn = random.choice([random_vehicle_number(), "", random_color()])
        y = random.choice([random_datetime(), "", random_make()])
        m = random.choice([random_make(), ""])
        mo = random.choice([random_model(), ""])
        ec = random.choice([random.randint(800, 4500), random_day(), ""])
        col = random.choice([random_color(), ""])
        dd = random_damage()
        tld = random.choice(["Repair", "TotalLoss", "TotalLoss/Repair", ""])
        pav = random.randint(500, 100000000)
        rc = random.choice(
            [repair_cost(tld, pav), "", random.randint(1, 99999999999999999999999)]
        )
        amfv = random.choice(
            [random.randint(10, 100000), "", random_damage()]
        )
        pn = random.choice([policy_number(), "", random_make()])
        ddob = random.choice([random_day(), "", random_color()])
        ft = random.choice(
            [
                "DIESEL",
                "DIESEL/ELECTRIC",
                "DIESEL/MHEV",
                "ELECTRIC",
                "PETROL",
                "PETROL/ALCOHOL",
                "PETROL/ELECTRIC",
                "PETROL/LPG",
                "",
                random_make(),
                random_color(),
            ]
        )
        d = random.choice(["0", "2", "3", "4", "5", "6", "", random_make()])
        s = random.choice(
            ["0", "2", "3", "4 ", "5", "6", "7", "8", "9", random_color(), ""]
        )
        id = random.choice([random_day(), "", random_color()])

    return [
        mid,
        ld,
        vrn,
        y,
        m,
        mo,
        ec,
        col,
        dd,
        tld,
        pav,
        rc,
        amfv,
        pn,
        ddob,
        ft,
        d,
        s,
        id,
    ]


with open("src_motor.csv", "w", newline="") as csvfile:
    field_names = [
        "mid",
        "ld",
        "vrn",
        "y",
        "m",
        "mo",
        "ec",
        "col",
        "dd",
        "tld",
        "pav",
        "rc",
        "amfv",
        "pn",
        "ddob",
        "ft",
        "d",
        "s",
        "id",
    ]
    writer = csv.writer(csvfile)
    writer.writerow(field_names)

    for item in range(rows_number):
        if random.random() < data_quality_percentage / 100:
            row = generate_data(True)
        else:
            row = generate_data(False)
        writer.writerow(row)
        if random.random() < data_duplicates_percentage / 100:
            row[15] = policy_number()
            writer.writerow(row)
